name: "basic-mart"
services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_serviceCont
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/code
    depends_on:
      - postgres_db


  # email:
  #   build:
  #     context: ./email
  #     dockerfile: Dockerfile
  #   container_name: email_service_Cont
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./email:/code
  #   depends_on:
  #     - postgres_db
  # inventory:
  #   build:
  #     context: ./Inventory
  #     dockerfile: Dockerfile
  #   container_name: Inventory_service_Cont
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./Inventory:/code
  #   depends_on:
  #     - postgres_db

  # notification:
  #   build:
  #     context: ./notification
  #     dockerfile: Dockerfile
  #   container_name: notification_service_Cont
  #   ports:
  #     - "8003:8003"
  #   volumes:
  #     - ./notification:/code
  #   depends_on:
  #     - postgres_db
  
  # order:
  #   build:
  #     context: ./order
  #     dockerfile: Dockerfile
  #   container_name: order_service_Cont
  #   ports:
  #     - "8004:8004"
  #   volumes:
  #     - ./order:/code
  #   depends_on:
  #     - postgres_db

  # payment:
  #   build:
  #     context: ./payment
  #     dockerfile: Dockerfile
  #   container_name: payment_service_Cont
  #   ports:
  #     - "8005:8005"
  #   volumes:
  #     - ./payment:/code
  #   depends_on:
  #     - postgres_db


  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtpCount
    ports:
      - "8006:8006"

  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgresCont
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hamid2264
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      TUNNEL_URL: http://api:8000
    command: "tunnel --no-autoupdate"
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - auth_service

volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge